import React from 'react';

export default props => (
    <div>
        <h1 className="center">Movie Quotes</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam, culpa blanditiis. Rem quisquam itaque molestias ipsum odio, repellendus deserunt numquam necessitatibus amet cupiditate! Laboriosam illo iure deserunt nobis. Ea incidunt eius dolor, iusto officia tempora eaque ut dolores voluptatibus eligendi laboriosam esse repudiandae atque veniam mollitia vel animi, necessitatibus rerum, reprehenderit molestiae id. Dolore cupiditate quia eveniet ab ea corporis repellat, reprehenderit ducimus cumque fugiat facilis. Culpa perspiciatis ipsa porro in at ullam sit, eum sunt eos asperiores dolorem velit cum nulla architecto illo voluptatibus aut tempore inventore rerum repellendus ipsum quaerat consequuntur dolore. Facere molestias eum iste mollitia error.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam atque, hic dicta repellendus odio maxime libero voluptatibus est officia, earum magnam. Totam fugiat consequatur culpa dolorem. Numquam vel error culpa vitae aliquam ex id tenetur veritatis expedita. Itaque ducimus quod eum recusandae ipsa magnam, atque eaque deserunt voluptate eveniet tempore consectetur mollitia omnis? Quibusdam cupiditate asperiores libero consequatur? Aperiam nemo quod cum, officia suscipit ex quia obcaecati aliquid eligendi, perspiciatis accusamus alias earum error voluptas fugiat quo nesciunt animi sit quas? Et, nihil atque dignissimos ipsam autem dicta culpa dolorem odit itaque distinctio nemo nulla id minus beatae explicabo sequi aperiam commodi voluptates corporis maiores quia minima exercitationem nisi. Dignissimos, ab modi? Ea quos error tempore, dolores quae distinctio sapiente.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. In earum mollitia sint quo officiis neque qui officia suscipit culpa quod reprehenderit, inventore blanditiis doloribus id aliquam perspiciatis, incidunt asperiores ducimus, non nostrum! Facere placeat explicabo qui laboriosam repudiandae facilis aspernatur rerum molestiae blanditiis, sapiente dignissimos pariatur dolorem doloribus ipsa illum eaque beatae et possimus. Tenetur consequatur fugit ducimus est adipisci tempore unde blanditiis praesentium provident? Veniam sit et nobis aut assumenda ab unde deserunt quaerat iure exercitationem, incidunt sunt corporis repudiandae maxime doloribus obcaecati voluptas quis necessitatibus quia officiis cupiditate at soluta. Doloribus amet fugit cupiditate magnam.</p>
    </div>
)